const stateTypes = {
    unknown: 0,
    socket: 1,
    light: 2,
    blind: 4,
    valve: 5,
    rgb: 6,
    dimmer: 7,
    temperature: 8,
    humidity: 9,
    lock: 10,
    button: 11,
    door: 12,
    window: 13,
    windowTile: 14,
    media: 15,
    thermostat: 16,
    camera: 17,
    motion: 18,
    fireAlarm: 19,
    floodAlarm: 20,
    gate: 21,
};

export default stateTypes;